-- MySQL Script generated by MySQL Workbench
-- 11/18/19 12:59:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ubs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ubs` (
  `UbsID` INT NOT NULL AUTO_INCREMENT,
  `UbsName` VARCHAR(45) NOT NULL,
  `UbsAddress` VARCHAR(45) NOT NULL,
  `UbsCnpj` VARCHAR(45) NOT NULL,
  `UbsContact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UbsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attendant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attendant` (
  `AttendantID` INT NOT NULL AUTO_INCREMENT,
  `AttendantCpf` VARCHAR(45) NOT NULL,
  `AttendantEmail` VARCHAR(45) NOT NULL,
  `AttendantName` VARCHAR(45) NOT NULL,
  `AttendantPass` VARCHAR(45) NOT NULL,
  `UbsID` INT NOT NULL,
  PRIMARY KEY (`AttendantID`, `UbsID`),
  INDEX `fk_Atendente_UBS1_idx` (`UbsID` ASC),
  CONSTRAINT `fk_Att_UbsID`
    FOREIGN KEY (`UbsID`)
    REFERENCES `mydb`.`Ubs` (`UbsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `UserCpf` VARCHAR(45) NOT NULL,
  `UserEmail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine` (
  `VaccineID` INT NOT NULL AUTO_INCREMENT,
  `VaccineName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VaccineID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependent` (
  `DependentID` INT NOT NULL AUTO_INCREMENT,
  `DependentName` VARCHAR(45) NOT NULL,
  `DependentBirth` DATE NOT NULL,
  `DependentBlood` CHAR(3) NOT NULL,
  `DependentAllergy` VARCHAR(45) NOT NULL,
  `DependentSusNo` VARCHAR(15) NOT NULL,
  `User_UserID` INT NOT NULL,
  PRIMARY KEY (`DependentID`, `User_UserID`),
  INDEX `fk_Dependent_User1_idx` (`User_UserID` ASC),
  CONSTRAINT `fk_Dependent_User1`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine_Dep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine_Dep` (
  `VaccineDate` DATE NOT NULL,
  `VaccineID` INT NOT NULL,
  `DependentID` INT NOT NULL,
  PRIMARY KEY (`VaccineID`, `DependentID`),
  INDEX `fk_Vacina_idx` (`VaccineID` ASC),
  INDEX `fk_Dep_idx` (`DependentID` ASC),
  CONSTRAINT `fk_Vacina`
    FOREIGN KEY (`VaccineID`)
    REFERENCES `mydb`.`Vaccine` (`VaccineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dep`
    FOREIGN KEY (`DependentID`)
    REFERENCES `mydb`.`Dependent` (`DependentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Dep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Dep` (
  `User_UserID` INT NOT NULL,
  `Dep_DependentID` INT NOT NULL,
  PRIMARY KEY (`User_UserID`, `Dep_DependentID`),
  INDEX `fk_Usuario_has_Dependentes_Dependentes1_idx` (`Dep_DependentID` ASC),
  INDEX `fk_Usuario_has_Dependentes_Usuario1_idx` (`User_UserID` ASC),
  CONSTRAINT `fk_Usuario_has_Dependentes_Usuario1`
    FOREIGN KEY (`User_UserID`)
    REFERENCES `mydb`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Dependentes_Dependentes1`
    FOREIGN KEY (`Dep_DependentID`)
    REFERENCES `mydb`.`Dependent` (`DependentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dose` (
  `DoseID` INT NOT NULL AUTO_INCREMENT,
  `DoseType` VARCHAR(45) NULL,
  `VaccineID` INT NOT NULL,
  PRIMARY KEY (`DoseID`, `VaccineID`),
  INDEX `fk_Vaccine_idx` (`VaccineID` ASC),
  CONSTRAINT `fk_Vaccine`
    FOREIGN KEY (`VaccineID`)
    REFERENCES `mydb`.`Vaccine` (`VaccineID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
